### PR TITLE
Fix warning

### LINKED ISSUE #232: Apk crashes when selects the video--v1.3.5_alpha.2
Apk crashes while playing the video, whether its chosen from the top header or side drawer crashing occurs.
**Steps to track the issue**
* open Apk ---> previously chosen book will open --> choose any video from the top header or side drawer ---> **apk crashes**
* do any change in book or language --> select any video from top header or side drawer --> first time video plays well --> choose any random video for the second time --> **Apk crashes**

### PR DESCRIPTION
**Pull request by Poojanavgurukul**
fixed #232 ,#215

### CODE REVIEW

File: app/screens/Video/index.js [hunk 1]
```diff
@@ -1,57 +1,90 @@
-import React, { useEffect, useState } from "react";
+import React, { useEffect, useRef, useState, useContext } from "react";
```
Comment (RevantCI) [inline app/screens/Video/index.js:1]: We can reomve useRef as its not used

File: app/screens/Video/index.js [hunk 2]
```diff
@@ -1,57 +1,90 @@
...
 import { Toast } from "native-base";
 import vApi from "../../utils/APIFetch";
 import ListContainer from "../../components/Common/FlatList.js";
+import { MainContext } from "../../context/MainProvider.js";
 const Video = (props) => {
   const bookId = props.route.params ? props.route.params.bookId : null;
   const bookName = props.route.params ? props.route.params.bookName : null;
+  const { bookList } = useContext(MainContext);
   const [videos, setVideos] = useState([]);
+  const [isLoading, setIsLoading] = useState(false);
```
Comment (RevantCI) [inline app/screens/Video/index.js]: We can remove isLoading and setIsLoading as it's not used

File: app/screens/Video/index.js [hunk 3]
```diff
@@ -1,57 +1,90 @@
...
-          duration: 8000,
-          position: "top",
-        });
+      if (found) {
+        setVideos(videoBook);
+        setMessage("");
+        setIsLoading(false);
+      } else {
+        if (bookId) {
+          // ToastAndroid.showWithGravityAndOffset(
```
Comment (RevantCI) [inline app/screens/Video/index.js]: We can remote this comment if its not required

File: app/screens/Video/index.js [hunk 4]
```diff
@@ -1,57 +1,90 @@
...
+          Toast.show({
+            text:
+              "Video for " +
+              bookName +
+              " is unavailable. You can check other books",
+            duration: 8000,
+            position: "top",
+          });
+        }
+        var elements = videoAll.reduce(function (previous, current) {
```
Comment (RevantCI) [inline app/screens/Video/index.js:61]: Before settings videosAll/elements if we can also sort it by bookid ie gen(1) to rev(66) it would be nice. If there are any issues just leave it for now we can do it in the next release. 1.3.6

File: app/screens/Audio/index.js [hunk 5]
```diff
@@ -44,21 +44,25 @@ const Audio = (props) => {
...
     );
   };
-  const audioData = async () => {
+
+  const audioData = () => {
     try {
       if (bookList) {
-        const audioBooks = props.audioList && props.audioList[0].books;
+        const audioBooks = props.audioList[0].books;
+        console.log(audioBooks, "audioBooks");
```
Comment (RevantCI) [inline app/screens/Audio/index.js]: Console.log can be removed from all places in the file

File: app/context/BibleContextProvider.js [hunk 6]
```diff
@@ -123,13 +123,11 @@ const BibleContextProvider = (props) => {
...
   };
   const updateLayout = () => {
-    if (arrl != undefined) {
-      let item = arrl.filter((i) => i?.verseNumber == verseNum);
-      if (item.length > 0) {
-        if (item[0].verseNumber == verseNum) {
-          const offset = getOffset(verseNum - 1);
-          verseScroll.current.scrollToOffset({ offset, animated: true });
-        }
+    let item = arrl?.filter((i) => i?.verseNumber == verseNum);
```
Comment (RevantCI) [inline app/context/BibleContextProvider.js:126]: We can put ?. optional chaining for item?.length also below

**Review by RevantCI — CHANGES_REQUESTED** [review]

**Review by RevantCI — CHANGES_REQUESTED** [review]
Hi Pooja have finished reviewing the changes there are few small changes, the bookId sorting if its taking time you can leave it.

**Review by RevantCI — APPROVED** [review]
